config/routes.rb
Rails.application.routes.draw do


  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  root 'songs#index'

  
  get '/about', to: 'static_pages#about'

  
  
  get '/signup', to: 'users#new'
  
  
  resources :songs
  
  resources :songs do
    member do
	  put "like" => "songs#upvote"
	end
  end
  
  resources :users
  
  post '/signup',  to: 'users#create'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord

  acts_as_votable
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: {case_sensitive: false}
  validates :artist, presence: true, length: { maximum: 40 }
  validates :anime, presence: true, length: { maximum: 100 }
  validates :nbre_vote, presence: true, numericality: true, inclusion: { in: 0..1000 }
  has_attached_file :photo
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ApplicationRecord

  acts_as_voter
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :set_event, only: [ :upvote ]
  
  def new
	@song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def show
	@song = Song.find(params[:id])
  end
  
  def index
	@songs = Song.all.order(:cached_votes_up => :desc)
  end
  
  def upvote
	@song.upvote_from current_user
	respond_to do |format|
    format.html { redirect_to :back }
    format.js
    end
  end
  
  def set_event
	@song = Song.find(params[:id])
  end
  
   def song_params
      params.require(:song).permit(:name, :artist, :anime, :nbre_vote, :photo)
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	@user = User.new
  end
  
  def show
	@user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
		log_in @user
		flash[:success] = "Bienvenue sur AniSongs!"
        redirect_to @user
    else
      render 'new'
    end
  end
  
  def index
	@user = User.all
  end
  
  private
  
  def user_params
	params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
  

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "AniSongs"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_head.html.erb
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-sm bg-primary navbar-dark fixed-top ">
  <div class="container">
  <ul class="nav navbar-nav pull-sm-left">
  <li class="nav-item active" id="logo">
  <%= link_to "AniSongs",   root_path, class: "nav-link" %>
  </li>
  </ul>
  <ul class="navbar-nav pull-sm-right">
    <li class="nav-item">
      <%= link_to "Accueil",   root_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "À Propos",   about_path, class: "nav-link" %>
    </li>
	 <% if logged_in? %>
     <li><%= link_to "Utilisateurs", '#', class: "nav-link" %></li>
	 <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              Mon Compte
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Mon Profil", current_user %></li>
              <li><%= link_to "Mes Paramètres", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Me déconnecter", logout_path, method: :delete %>
              </li>
            </ul>
     </li>
     <% else %>
        <li class="nav-item"><%= link_to "Me connecter", login_path, class: "nav-link" %></li>
     <% end %>
  </ul>
 </div>
</nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>

app/views/shared/_error_messages.html.erb
<% if @song.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@song.errors.count, "error") %>.
    </div>
    <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


app/views/shared/_error_messages_user.html.erb
<% if @user.errors.any? %>
 <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/songs/index.html.erb
<% provide(:title, "Accueil") %>

<div class="center jumbotron">
  <h2>
    Vous n'êtes jamais d'accord avec vos amis sur les meilleures musiques d'animes sorties cette saison ? Votez pour vos musiques d'animes
	préférées et découvrez les plus populaires de la saison ! 
  </h2>
  <%= link_to "M'inscrire!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<style>
    .card-custom {
        max-width: 200px;
    }
</style>

<h1>Toutes les chansons de la saison</h1>
<div class="container">
   <div class="row mt-5">
  <% @songs.each do |song| %>
    <div class="card card-custom mx-2 mb-3" >
		<%= link_to song do %>
		<%= image_tag song.photo.url, size: "200x200", class: "card-img-top" %>
		<% end %>
		<div class="card-body d-flex flex-column ">
			<h4 class="card-title"><%= song.name %></h4>
			<p class="card-text"><%= song.anime %></p>
			<% if logged_in? %>
				<% if current_user.voted_on?(song) %>
					<%= link_to like_song_path(song), id: "upvote_#{song.id}", method: :put, class: "btn btn-danger btn-lg mt-auto round", remote: true do %>
					<span class="glyphicon glyphicon-thumbs-up"></span> J'aime
					<% end %>
				<% else %>
					<%= link_to like_song_path(song), id: "upvote_#{song.id}", method: :put, class: "btn btn-outline-danger btn-lg mt-auto round", remote: true do %>
					<span class="glyphicon glyphicon-thumbs-up"></span> J'aime
					<% end %>
				<% end %>
			<% end %>
		</div>
	</div>
        
  <% end %>

</div>
</div>

app/views/songs/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@song) do |f| %>
		<%= render 'shared/error_messages' %>

	
      <%= f.label :name, "Nom" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :artist, "Artiste" %>
      <%= f.text_field :artist, class: 'form-control' %>

      <%= f.label :anime, "Anime" %>
      <%= f.text_field :anime, class: 'form-control' %>

      <%= f.label :nbre_vote, "Nombre de votes" %>
      <%= f.text_field :nbre_vote, class: 'form-control' %>
	  
	  <%= f.label :photo, "Image" %>
      <%= f.file_field :photo %>

      <%= f.submit "Ajouter chanson", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/songs/show.html.erb
<p><%= image_tag @song.photo.url, :size => "200x200" %><p>
<%= @song.name %>, <%= @song.artist %>, <%= @song.anime %>, <%= @song.get_upvotes.size %>
<iframe width="560" height="315" src="https://www.youtube.com/embed/Mr3tRGvmcBs" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

app/views/songs/upvote.js.erb
$("#upvote_<%= @song.id %>").removeClass("btn-outline-danger").addClass("btn-danger")

app/views/static_pages/about.html.erb
<% provide(:title, "A propos") %>
<h1>A propos d'AniSongsList</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Accueil") %>

<div class="center jumbotron">
  <h2>
    Vous n'êtes jamais d'accord avec vos amis sur les meilleures musiques d'animes sorties cette saison ? Votez pour vos musiques d'animes
	préférées et découvrez les plus populaires de la saison ! 
  </h2>
  <%= link_to "M'inscrire!", root_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-4 offset-md-4">
     <%= form_for(@user, url: signup_path) do |f| %>
	  <%= render 'shared/error_messages_user' %>

	
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary button-bottom" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>